
CREATE TABLE TRANSACTION
(
  	AMOUNT 				NUMBER NOT NULL,
	PAN 				VARCHAR(32 CHAR) NOT NULL,
	ACCOUNT_ID 			NUMBER NOT NULL,
	CUSTOMER_ID 		NUMBER NOT NULL,
	CUSTOMER_NAME 		VARCHAR(32 CHAR),
	MERCHANT_ID 		NUMBER NOT NULL,
	MERCHANT_NAME 		VARCHAR(32 CHAR),
	TRANSACTION_DATE 	TIMESTAMP NOT NULL
);
