-- DROP TABLE USERS;

CREATE TABLE USERS
(
  "USER_ID"           NUMBER NOT NULL PRIMARY KEY,
  "USERNAME"          VARCHAR(32 CHAR) NOT NULL UNIQUE,
  "FIRSTNAME"         VARCHAR(32 CHAR) NOT NULL,
  "LASTNAME"          VARCHAR(32 CHAR) NOT NULL,
  "AGE"               NUMBER
);

INSERT INTO USERS (USER_ID, USERNAME, FIRSTNAME, LASTNAME, AGE) VALUES (1, 'johndoe', 'John',  'Doe',   25);
INSERT INTO USERS (USER_ID, USERNAME, FIRSTNAME, LASTNAME, AGE) VALUES (2, 'adi',     'Adi',   'Dozsa', 30);
INSERT INTO USERS (USER_ID, USERNAME, FIRSTNAME, LASTNAME, AGE) VALUES (3, 'bogdan',  'Bogdan','Solga', 32);
INSERT INTO USERS (USER_ID, USERNAME, FIRSTNAME, LASTNAME, AGE) VALUES (4, 'adrian',  'Adi',   'Popa',  28);